src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductCartItem__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>ProductCartItems</relationshipLabel>
        <relationshipName>ProductCartItems</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>ProductCartItems</relationshipLabel>
        <relationshipName>ProductCartItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductCartItem</label>
    <nameField>
        <label>ProductCart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductCartItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CartItemRepository.cls
public class CartItemRepository {

	public void create(Id opportunityId, Id product2Id) {
		ProductCartItem__c cartItem = new ProductCartItem__c(
				Opportunity__c = opportunityId,
				Product__c = product2Id
		);

		// TODO : I guess that we have a better way to prevent duplicates, but this used as a quick workaround
		List<ProductCartItem__c> duplicates = [
				select Id
				from ProductCartItem__c
				where Opportunity__c = :opportunityId
				and Product__c = :product2Id
		];

		if (Util.notEmpty(duplicates)) {
			System.debug(LoggingLevel.ERROR,
							'Prevent attempting to add Cart Item duplication: ' +
							'Opportunity ID = ' + opportunityId + ' Product2 ID = ' + product2Id);
			return;
		}

		insert cartItem;
	}

	public List<ProductCartItem__c> finAllBy(Id opportunityId) {
		return [
				select Id,
						Opportunity__c,
						Product__c
				from ProductCartItem__c
				where Opportunity__c = :opportunityId
		];
	}
}