src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductFamily__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ProductFamily</label>
        <referenceTo>ProductFamily__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ProductType</label>
        <referenceTo>ProductType__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductFamily__c.object
<CustomObject>
    <label>ProductFamily</label>
    <nameField>
        <label>ProductFamily Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductFamilies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductType__c.object
<CustomObject>
    <label>ProductType</label>
    <nameField>
        <label>ProductType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductRepository.cls
public class ProductRepository {

	public List<Product__c> getProductsWhere(String descriptionPattern,
											 List<String> familiesNames,
											 List<String> typesNames) {

		String queryBuilder =
				'select Id,' +
				' Name,' +
				' Price__c,' +
				' Description__c,' +
				' IconLink__c,' +
				' ProductLink__c,' +
				' ProductFamily__r.Name,' +
				' ProductType__r.Name ' +
				'from Product__c';

		List<String> whereClauses = new List<String>();
		if (Util.notEmpty(descriptionPattern)) {
			// prevent SOQL injections
			String normalized = String.escapeSingleQuotes(descriptionPattern);
			whereClauses.add('Description__c like \'%' + normalized + '%\'');
		}

		if (Util.notEmpty(familiesNames)) {
			whereClauses.add('ProductFamily__r.Name in :familiesNames');
		}

		if (Util.notEmpty(typesNames)) {
			whereClauses.add('ProductType__r.Name in : typesNames');
		}

		if (!whereClauses.isEmpty()) {
			queryBuilder = queryBuilder + ' where ' + String.join(whereClauses, ' and ');
		}

		System.debug('[queryBuilder::String]:watches' + JSON.serialize(queryBuilder));
		return Database.query(queryBuilder);
	}
}